apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:

    - name: nginx-container
      image: nginx:1.10

    - name: client
      image: curlimages/curl:7.76.0
      command: ["/bin/sh"]
      args: [ "-c", "while true; do curl -s http://localhost:8080/date;sleep 2;done" ]